# This is X-R1(https://github.com/dhcode-cpp/X-R1) project training config:
# required >=  4x3090(24G)/4090(24G)
# running time 2~3h

# Model arguments
model_name_or_path: Qwen/Qwen2.5-3B
model_revision: main
torch_dtype: bfloat16
attn_implementation: flash_attention_2

# Data training arguments
dataset_name: xiaodongguaAIGC/X-R1-750
dataset_configs:
- train
num_processes: 3
max_train_samples: 100
max_val_samples: 50

# GRPO trainer config
wandb_project: "X-R1-dev"
bf16: true
use_vllm: true
vllm_device: auto
vllm_gpu_memory_utilization: 0.7
do_eval: false
eval_strategy: "epoch"
eval_steps: 30
gradient_accumulation_steps: 8
gradient_checkpointing: true
gradient_checkpointing_kwargs:
  use_reentrant: false
learning_rate: 3.0e-06
log_level: info
logging_steps: 10
logging_strategy: "steps"
log_completions: true
lr_scheduler_type: cosine
max_prompt_length: 256
num_generations: 6
temperature: 0.9
temperature_schedule:
  type: "step"
  start: 0.9
  steps: [[1, 0.9]] 
advantage_offset: 0.0
max_completion_length: 1024
max_steps: -1
num_train_epochs: 30
output_dir: output/X-R1-3B
overwrite_output_dir: true
per_device_eval_batch_size: 2
per_device_train_batch_size: 2
push_to_hub: False
report_to:
- wandb
save_strategy: "no"
save_steps: 100
seed: 42
warmup_ratio: 0.1

#beta: 0.0
