# This is X-R1(https://github.com/dhcode-cpp/X-R1) project training config:
# required >=  8 x 80G GPU
# running time ~32h

# Model arguments
model_name_or_path: Qwen/Qwen2.5-7B
model_revision: main
torch_dtype: bfloat16
attn_implementation: flash_attention_2

# Data training arguments
#dataset_name: xiaodongguaAIGC/X-R1-7500 # 750 / 1500 / 7500
# eval_dataset_name: HuggingFaceH4/aime_2024
dataset_name: phiyodr/coco2017
dataset_configs:
- train
num_processes: 7
max_train_samples: 3000
max_val_samples: 10
dataset_test_split: validation

# GRPO trainer config
wandb_project: "X-R1-SGP"
use_vllm: true
output_dir: output/X-R1-7B
gradient_accumulation_steps: 8
max_prompt_length: 256
num_generations: 7
temperature: 0.9
temperature_schedule:
  type: "step"
  start: 0.9
  steps: [[1, 0.9]] 
advantage_offset: 0.0
logp_variance_reg_coef: 0.0
max_completion_length: 1024

bf16: true
vllm_device: auto
vllm_gpu_memory_utilization: 0.5
do_eval: false
eval_strategy: "steps"
eval_steps: 30
gradient_checkpointing: true
gradient_checkpointing_kwargs:
  use_reentrant: false
learning_rate: 3.0e-06
log_level: info
logging_steps: 10
logging_strategy: steps
lr_scheduler_type: constant
max_steps: -1
num_train_epochs: 1
overwrite_output_dir: true
per_device_eval_batch_size: 4
per_device_train_batch_size: 4
push_to_hub: False
report_to:
- wandb
save_strategy: "steps"
save_steps: 40
seed: 42
warmup_ratio: 0.01
