# This is X-R1(https://github.com/dhcode-cpp/X-R1) project training config:
# required >=  4x3090(24G)/4090(24G)
# running time 2~3h

# Model arguments
model_name_or_path: Qwen/Qwen2.5-3B-Instruct
model_revision: main
torch_dtype: bfloat16
attn_implementation: flash_attention_2

# Data training arguments
#dataset_name: xiaodongguaAIGC/X-R1-7500 # 750 / 1500 / 7500
# eval_dataset_name: HuggingFaceH4/aime_2024
# dataset_name: uwunion/instruct_svg
dataset_name: simple_object
# dataset_name: uoft-cs/cifar100
# dataset_name: sgp-bench/sit_55k
dataset_configs:
- train
num_processes: 7
max_train_samples: 3000
max_test_samples: 10
# dataset_test_split: validation
# dataset_test_split: test


# GRPO trainer config
epsilon: 0.02
wandb_project: "X-R1-SGP"
use_vllm: true
output_dir: output/X-R1-7B
gradient_accumulation_steps: 8
max_prompt_length: 256
num_generations: 7
temperature: 0.7
top_p: 0.8
temperature_schedule:
  type: "step"
  start: 0.7
  steps: [[1, 0.7]] 
advantage_offset: 0.0
logp_variance_reg_coef: 0.0
max_completion_length: 1024

bf16: true
vllm_device: auto
vllm_gpu_memory_utilization: 0.5
do_eval: false
eval_strategy: "no"
eval_steps: 30
gradient_checkpointing: true
gradient_checkpointing_kwargs:
  use_reentrant: false
learning_rate: 3.0e-06
log_level: info
logging_steps: 5
logging_strategy: steps
log_completions: true

lr_scheduler_type: cosine
max_steps: -1
num_train_epochs: 10
overwrite_output_dir: true
per_device_eval_batch_size: 4
per_device_train_batch_size: 4
push_to_hub: False
report_to:
- wandb
save_strategy: "steps"
save_steps: 10
seed: 42
warmup_ratio: 0.1
